version: '3.7'

x-common-kafka-environment: &common-kafka-environment
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_MIN_INSYNC_REPLICAS: 1
  KAFKA_NUM_PARTITIONS: 3
  KAFKA_LOG_RETENTION_HOURS: 24
  KAFKA_LOG_RETENTION_BYTES: 1073741824 # 1GB
  KAFKA_DELETE_TOPIC_ENABLE: true
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: true # default it also true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    hostname: zookeeper
    container_name: EVENTS-zookeeper
    ports:
      - "2181:2181"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka1
    container_name: EVENTS-kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_BROKER_ID: 1
      <<: *common-kafka-environment
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka2
    container_name: EVENTS-kafka2
    ports:
      - "9093:9093"
      - "29093:29093"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
      KAFKA_BROKER_ID: 2
      <<: *common-kafka-environment
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka3
    container_name: EVENTS-kafka3
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,DOCKER://host.docker.internal:29094
      KAFKA_BROKER_ID: 3
      <<: *common-kafka-environment
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    hostname: schema-registry
    container_name: EVENTS-schema-registry
    ports:
      - "3690:8081"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:19092,PLAINTEXT://kafka3:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3

  postgresql:
    image: postgres:14
    hostname: postgresql
    container_name: EVENTS-postgresql
    ports:
      - "5431:5432"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    environment:
      POSTGRES_DB: "conductor_db"
      POSTGRES_USER: "conductor"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.31.0
    hostname: conduktor-console
    container_name: EVENTS-conduktor-console
    depends_on:
      - postgresql
    ports:
      - "1001:8080"
    volumes:
      - type: bind
        source: "./kafka-ui-helper-config.yml"
        target: /opt/conduktor/platform-config.yaml
        read_only: true
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: adminP4ss!
      AUTH_LOCAL_USERS: user@user.com:userP4ss!