version: "3.8"
services:
  micro_forum_config-server:
    image: feeham/open_forum_configserver:latest
    container_name: config-server
    ports:
      - "8888:8888"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s

  micro_forum_discovery-server:
    image: feeham/open_forum_discoveryserver:latest
    container_name: discovery-server
    ports:
      - "7777:7777"
    extends:
      file: config-prefixes.yml
      service: common-config-after-config-server
    healthcheck:
      test: "curl --fail --silent localhost:7777/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s

  micro_forum_posts:
    image: feeham/open_forum_posts:latest
    container_name: posts
    ports:
      - "3100:3100"
    environment:
      SPRING_PROFILES_ACTIVE: "testing"
    depends_on:
      - post-service-pg-db
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server

  micro_forum_notifications:
    image: feeham/open_forum_notification:latest
    container_name: notifications
    ports:
      - "3400:3400"
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server

  micro_forum_gateway:
    image: feeham/open_forum_gateway:latest
    container_name: gateway
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: "testing"
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server
