version: "3.8"
services:
  open_forum_config-server:
    image: feeham/open_forum_configserver:latest
    container_name: OPEN_FORUM_CLOUD-config-server
    ports:
      - "8888:8888"
    extends:
      file: config-prefixes.yml
      service: common-config-initial
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 3s
      timeout: 1s
      retries: 50
      start_period: 2s

  open_forum_discovery-server:
    image: feeham/open_forum_discoveryserver:latest
    container_name: OPEN_FORUM_CLOUD-discovery-server
    ports:
      - "7777:7777"
    extends:
      file: config-prefixes.yml
      service: common-config-after-config-server
    healthcheck:
      test: "curl --fail --silent localhost:7777/actuator/health/readiness | grep UP || exit 1"
      interval: 3s
      timeout: 1s
      retries: 50
      start_period: 2s

  open_forum_gateway:
    image: feeham/open_forum_gateway:latest
    container_name: OPEN_FORUM_CLOUD-gateway
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: "testing"
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server

  open_forum_posts:
    image: feeham/open_forum_posts:latest
    container_name: OPEN_FORUM_CORE-posts
    ports:
      - "3100:3100"
    environment:
      SPRING_PROFILES_ACTIVE: "testing"
    depends_on:
      - post-service-pg-db
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server

  open_forum_notifications:
    image: feeham/open_forum_notification:latest
    container_name: OPEN_FORUM_CORE-notifications
    ports:
      - "3400:3400"
    extends:
      file: config-prefixes.yml
      service: common-config-after-discovery-server

networks:
  open-forum-network:
    name: open-forum-network
    external: true