version: '3.8'
services:
  # Postgres database for post-service
  storage-post-service-pg-db:
    image: postgres:14.15-alpine3.20
    container_name: STORAGE_POSTGRES_FOR-post-service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: post-service-pg-db
      POSTGRES_USER: post-service-pg-db_user
      POSTGRES_PASSWORD: post-service-pg-db_password
    volumes:
      - post-service-pg-db_local_data:/var/lib/postgresql/data

  # Postgres database for post-service
  storage-review-service-pg-db:
    image: postgres:14.15-alpine3.20
    container_name: STORAGE_POSTGRES_FOR-review-service
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: review_db_user
      POSTGRES_PASSWORD: review_db_password
    volumes:
      - review-service-pg-db_local_data:/var/lib/postgresql/data

  storage-redis:
    image: redis
    container_name: STORAGE-redis
    ports:
      - "6379:6379"

networks:
  open-forum-network:
    name: open-forum-network
    external: true